crates/nu-cli/src/syntax_highlight.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-parser/tests/test_parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/expression.rs, crates/nu-protocol/src/ast/operator.rs, crates/nu-protocol/src/ty.rs, crates/nu-protocol/src/value.rs
Implements the following:
* `0..3` -> [0, 1, 2, 3]
* `0..<3` -> [0, 1, 2]
* `98..` -> [98, 99, 100]
* `98..<` -> [98, 99]
* subexpressions and variables as ranges bounds 
* `let a = 2; $a..(4 + $a)` -> [2, 3, 4, 5, 6]
* syntax highlighting
* one step towards stepping
* `0..2..10` detects the step in the middle but still parses it as `0..10`
Known bugs:
* `..10` doesn't work
* syntax highlighting for stepped ranges doesn't work for the middle part (might be resolved once stepping is fully implemented)
* works only for integers >= 0 and the range must be ascending
=> Implement positive integer ranges

crates/nu-command/src/each.rs, src/tests.rs
Allows you to do a trivial iteration over simple values:
```
> 4 | each { $it + 10 }
```
=> Simple value iteration

TODO.md, crates/nu-protocol/src/engine/evaluation_context.rs, src/tests.rs
This will convert values to their "concrete" form when assigning to a variable. ValueStream -> List, RowStream -> Table.
=> Concrete var assign

TODO.md, crates/nu-cli/src/errors.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/cell_path.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/mod.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/syntax_shape.rs, crates/nu-protocol/src/ty.rs, crates/nu-protocol/src/value.rs, src/tests.rs
Adds cell paths for variables and subexpressions.
These allow you to access data in rows, columns, and cells of lists, tables, value streams, and row streams.
Eg)
```
> ([[a b]; [[1 2] [3 4]]]).a
[[1, 2]]
> ([[a b]; [[1 2] [3 4]]]).a.0
[1, 2]
> ([[a b]; [[1 2] [3 4]]]).a.0.1
2
```
=> Add cell paths

crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-parser/tests/test_parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/operator.rs, crates/nu-protocol/src/value/mod.rs, crates/nu-protocol/src/value/range.rs
Follows the following syntax: `<start>..<next-value>..<end>`. In case some of the values is missing, it gets automatically inferred.
Also small refactor to the range iterator.
Examples (these should go into test suite once we have eval tests set up):
* `2..4..8` -> `[2, 4, 6, 8]`
* `2..4..<6` -> `[2, 4, 6]`
* `2..-2..-8` -> `[2, -2, -6]`
* `..2..6` -> parse error but should be equivalent to `0..2..6`
* `2..4..` -> equals to `2..4..100`
* `2..-4..` -> equals to `2..-4..-100`
* `2..6` -> `[2, 3, 4, 5, 6]`
* `2..-2` -> `[2, 1, 0, -1, -2]`
* `2..-2..-2` -> `[2, -2]`
Integer values only for now.
=> Add stepping support & reversing to ranges

crates/nu-parser/src/parser.rs, crates/nu-parser/tests/test_parser.rs
This allows parsing `..10` and similar as a left-unbounded range.
Some points:
* Valid path should not be parseable as a valid range because the only case you can have a path separator in a range is this: `0..(4 / 2)..10` which involves spaces. Paths should not have spaces around the separator (I hope?).
* `..` is not allowed to be parsed as a range. Range always needs at least one bound, otherwise it could be easily confused with parent directory.
* With this change, *external* commands with names that could be a valid range (e.g. `..10`) are not allowed since they would parse as a range.
* *Internal* commands named `..10` etc. are allowed.
=> Allow parsing left-unbounded range (..10)

TODO.md, crates/nu-command/src/benchmark.rs, crates/nu-command/src/def.rs, crates/nu-command/src/do_.rs, crates/nu-command/src/each.rs, crates/nu-command/src/for_.rs, crates/nu-command/src/if_.rs, crates/nu-parser/src/parser.rs, crates/nu-parser/src/type_check.rs, crates/nu-parser/tests/test_parser.rs, crates/nu-protocol/src/ast/call.rs, crates/nu-protocol/src/syntax_shape.rs, src/tests.rs
This adds block param shapes to block shapes (not yet as part of syntax). This allows commands to say whether or not they expect a block that takes a param.
This makes it easier to know when to imply that there is an `$it` in the param that's unnamed or not, as some commands will want this and others won't.
=> Block param types

crates/nu-engine/src/eval.rs
Externals now accept input from previous statements in the pipeline. This will be handy if we want to "feed" the external command via stdin
=> External with input

Cargo.lock, Cargo.toml, crates/nu-cli/Cargo.toml, crates/nu-cli/src/errors.rs, crates/nu-cli/src/lib.rs, crates/nu-parser/Cargo.toml, crates/nu-parser/src/errors.rs, crates/nu-protocol/Cargo.toml, crates/nu-protocol/src/engine/command.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/span.rs, src/main.rs, src/tests.rs
=> replace codespan-reporting with miette 3.0

Cargo.lock, crates/nu-cli/src/lib.rs, crates/nu-cli/src/validation.rs, crates/nu-parser/src/errors.rs, crates/nu-parser/src/lex.rs, src/main.rs
Implements initial validation. It's not quite there, but it does work.
Unclosed " and ' immediately go to the next line when you hit enter
Unclosed ( and { don't seem to move to the next line, but if you start typing you'll see you're on the next line.
Not sure if these are reedline or e-q issues
=> multiline validation

Cargo.lock, crates/nu-command/src/lines.rs, crates/nu-command/src/run_external.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/value/stream.rs
Corrected bug with channel. Using `sync_channel` was blocking some external commands, like `rg`.
Things that still need correction:
- When using `cat` (probably only windows) the prompt gets mangled and it can only be seen as bytes. It goes back to normal after typing something and pressing enter
- Python commands are not sent to stdout. If we send `python -c "print('hello')"` the output is missed. However we can enter a python shell without problem
- The use of `^` for marking and external command. Now `git` cannot be used because there is a git command in engine-q
=> Better print out for stream output

crates/nu-command/src/build_string.rs, crates/nu-command/src/default_context.rs, crates/nu-command/src/lines.rs, crates/nu-command/src/run_external.rs, crates/nu-command/src/table.rs, crates/nu-protocol/src/engine/engine_state.rs, src/main.rs
If the `Table` command is found in the command declarations, then it is used to format the output calculated from the evaluation stage.
Note: Only evaluations happening in interactive move are printed as tables. Files still maintain the old format to avoid errors with the tests
=> Table as string output

crates/nu-command/src/default_context.rs, crates/nu-command/src/lib.rs, crates/nu-command/src/module.rs, crates/nu-command/src/use_.rs, crates/nu-parser/src/errors.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/block.rs, crates/nu-protocol/src/engine/engine_state.rs
Introduces `module` and `use` keywords to define a module and import custom commands from it.
Current limitations:
* Currently, only custom commands are supported for export
* Also, all defs within a module are exported, there is no selective export yet, neither are the definitions hidden behind namespace
* `module` also closes over its parent scope which we probably want to disallow
* This could be handled by the same mechanic as deactivate: When entering a module scope, deactivate everything
* No module from file yet
* No deactivate yet
* No nested modules yet
* Modules are implemented as Blocks which expose what definitions are to be exported. However, we do not use the underlying Block anywhere at all, so we might change Module to be just a list of exportables.
* If we make `use` to …
=> Primitive module implementation

crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/import_pattern.rs, src/tests.rs
This adds a new import pattern, the list
```
use foo.[a, c];
c
```
=> Add import lists

Cargo.lock, Cargo.toml, src/main.rs
Without this change, the output of panic messages by miette would ignore
newlines and become unreadable.
=> Disable crossterm raw mode

crates/nu-cli/src/lib.rs, crates/nu-cli/src/prompt.rs, crates/nu-protocol/src/engine/evaluation_context.rs, src/main.rs
Introduces the ability to configure the prompt using the `PROMPT_COMMAND` env variable
=> Prompt with env variable

crates/nu-protocol/Cargo.toml
We want to be able to compile nu-protocol (standalone) by itself and run the nu-protocol tests.
By adding the derive feature to serde this works...
=> add serde derive to Cargo.toml so nu-protocol compiles standalone

crates/nu-command/src/filters/lines.rs
Trim should be a separate step, so you can do `lines` and join them with newlines to get back the original.
=> Lines shouldn't trim

crates/nu-parser/src/parse_keywords.rs, crates/nu-protocol/src/engine/engine_state.rs, src/tests.rs
This lets you hide custom commands by import pattern:
```
>  module spam { export def foo [] { "foo" } }
> use spam
> hide spam.*
...same as
> hide spam.foo
...same as
> hide spam.[foo]
```
There is currently a bug that won't let you `use` and `hide` repeatedly from a module. I'm addressing that in the next PR.
=> Add import patterns to 'hide'

Cargo.lock, Cargo.toml, crates/nu-cli/Cargo.toml, crates/nu-command/src/filters/get.rs
Change the location of the reedline repo to the nushell repo from jt
I believe the signature of the get command should read
```rust
Signature::build("get").required(
```
and it was mistakenly labeled wrap....
=> The signature of the get command was mistakenly named wrap

crates/nu-command/src/default_context.rs, crates/nu-command/src/filesystem/cp.rs, crates/nu-command/src/filesystem/mod.rs, crates/nu-command/src/filesystem/util.rs, crates/nu-protocol/src/shell_error.rs
This also includes a few fs utils for handling nested directory mapping and creation.  I added a few std::convert::From impls for ShellErrors as well, which are resolving to internal errors right now, but can probably be swapped out for more descriptive errors.
=> port `cp` to fs commands

crates/nu-engine/src/eval.rs, crates/nu-parser/src/type_check.rs, crates/nu-protocol/src/value/mod.rs, crates/nu-protocol/src/value/range.rs, src/tests.rs
- Port `in` and `not-in` operators
- Implement `PartialOrd` for `Value`
- Add `Range::contains` method
=> Add `in` and `not-in` operators support

crates/nu-command/src/core_commands/if_.rs, crates/nu-command/src/filters/each.rs, crates/nu-command/src/formats/from/json.rs, crates/nu-command/src/strings/split/chars.rs, crates/nu-command/src/strings/split/column.rs, crates/nu-command/src/strings/split/row.rs, crates/nu-engine/src/eval.rs, crates/nu-engine/src/from_value.rs, crates/nu-protocol/src/value/mod.rs, crates/nu-protocol/src/value/range.rs, src/tests.rs
This adds errors that come a bit earlier when possible. We don't want to underline an error value when we have one, instead, we should just report the error the error value points at.
=> Earlier errors

crates/nu-command/src/default_context.rs, crates/nu-command/src/math/avg.rs, crates/nu-command/src/math/max.rs, crates/nu-command/src/math/min.rs, crates/nu-command/src/math/mod.rs, crates/nu-command/src/math/reducers.rs
Added `math min` and `math max` all the outputs below are pretty much identical to the ones in the old engine.(The `ls`are done in the engine-q file.
```
〉ls | math min
╭──────┬──────╮
│ name │ .git │
│ type │ Dir  │
│ size │ 28 B │
╰──────┴──────╯
```
```
〉ls | math max
╭──────┬─────────╮
│ size │ 33.1 KB │
│ type │ File    │
│ name │ target  │
╰──────┴─────────╯
```
```
〉1 | math max 
1
```
```
〉1 | math min
1
```
```
〉[1 2 4 3] | math max 
4
```
```
〉[1 2 4 3] | math min
1
```
```
〉[[size, height, filesize]; [100, 40, 2TB] [60, 30, 1B]] | math max
╭──────────┬────────╮
│ height   │ 40     │
│ filesize │ 2.0 TB │
│ size     │ 100    │
╰──────────┴────────╯
```
```
〉[[size, height, filesize]; [100, 40, 2TB] [60, 30, 1B]] | math min
╭──────────┬─────╮
│ height   │ 30  │
│ size     │ 60  │ …
```
=> Added math and min commands

crates/nu-command/src/core_commands/use_.rs, crates/nu-parser/src/errors.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/engine/engine_state.rs, src/tests.rs
```
> module spam { def foo [] { "foo" } }
> use spam foo
> foo
```
```
> bash -c "echo 'export def foo [] { \"foo\" }' > spam.nu"
> use spam.nu
> spam foo
foo
> use spam.nu foo
> foo
foo
> hide foo
> hide spam *
```
Fixes #258.
See changes in `engine_state.rs` and a commit message in [7112664b](https://github.com/nushell/engine-q/pull/243/commits/7112664b3fb9caceb72bb6d302d33a5637ee0910)
Currently, the module loaded from file closes over existing scope, which means that local definitions will be visible. We probably do not want that but fixing it would require some thinking -- e.g., we should make some default "overlay" that would be visible but hide the user-defined stuff. So I'll leave it for a future PR.
=> Loading modules from files

crates/nu-command/src/core_commands/echo.rs, crates/nu-command/src/core_commands/mod.rs, crates/nu-command/src/default_context.rs
Implementation of command `echo`, assigned in #242.
I also ran `cargo clippy --all`, so that I was sure I didn't introduce unnecessary warnings.
I'll be waiting for feedback, before going on with `format`.
=> Porting echo command

Cargo.lock, crates/nu-command/src/default_context.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/lib.rs, src/main.rs, src/tests.rs
Adding a simple `$scope`. Currently, it just lists the names of variables, commands, aliases, and modules that are in scope at the current location. In the future, we could extend this with more info.
=> Add a simple scope variable

crates/nu-command/Cargo.toml, crates/nu-command/src/conversions/into/mod.rs, crates/nu-command/src/conversions/into/string.rs, crates/nu-command/src/default_context.rs
I ported most of `into string` command. We do not support the older column paths at the moment. I'd be happy to work more on this if I understand what's the output of `into string` when called on a table. It makes the specified column's values into strings?
=> Port into string command

Cargo.lock, crates/nu-command/src/filters/where_.rs, crates/nu-protocol/src/pipeline_data.rs, src/tests.rs
Moving `where` to a helper for PipelineData. This allows `where` to also work over ranges (like the other helpers)
=> Move where to helper

crates/nu-engine/src/eval.rs, crates/nu-parser/src/lex.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, src/tests.rs
This lets you write something like `[1, 2, 3].1` if you want. I think people will assume this is supported (I've even tripped a couple times when I forgot it wasn't).
Might as well add it if it doesn't hurt anything else. I think it's probably okay since it's hard for this to look like something else.
=> Let list and table exprs get indexed

crates/nu-command/src/default_context.rs, crates/nu-command/src/strings/str_/contains.rs, crates/nu-command/src/strings/str_/downcase.rs, crates/nu-command/src/strings/str_/mod.rs
Two more commands ported. I was wondering if the desired output for `str contains` on tables is to really modify the column's value to `true/false`. I could see also potential use cases where we need to know which rows contain that string pattern, and then this does not work nicely. Any thoughts?
=> Port str downcase and str contains

crates/nu-cli/src/syntax_highlight.rs
Surprisingly there are only 17 items in engine-q's FlatShape enum where there are 30 items in nushell's. I put comments on where I mapped the colors from nushell. It looks closer.
=> try to match most of nushell syntax coloring

Cargo.lock, crates/nu-command/src/core_commands/do_.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/expression.rs, crates/nu-protocol/src/value/mod.rs, src/tests.rs
This allows for a JSON-like record syntax:
```
let x = {"b": 5}
```
As well as hjson-like relaxed syntax:
```
let x = {b: 5}
```
=> Add record literal syntax

TODO.md, crates/nu-command/src/conversions/into/string.rs, crates/nu-command/src/example_test.rs, crates/nu-command/src/formats/from/csv.rs, crates/nu-command/src/formats/from/delimited.rs, crates/nu-command/src/formats/from/eml.rs, crates/nu-command/src/formats/from/json.rs, crates/nu-command/src/formats/from/tsv.rs, crates/nu-command/src/formats/from/url.rs, crates/nu-command/src/formats/from/yaml.rs, crates/nu-command/src/strings/build_string.rs, crates/nu-command/src/strings/str_/collect.rs, crates/nu-command/src/system/run_external.rs, crates/nu-command/src/viewers/griddle.rs, crates/nu-command/src/viewers/table.rs, crates/nu-engine/src/eval.rs, crates/nu-engine/src/from_value.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/config.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/engine/stack.rs, crates/nu-protocol/src/lib.rs, crates/nu-protocol/src/pipeline_data.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/value/mod.rs, crates/nu-protocol/src/value/row.rs, crates/nu-protocol/src/value/stream.rs, src/main.rs, src/tests.rs
This adds a new builtin variable `$config`. The `$config` variable allows users to update the config by setting this to a record with known fields.
I currently have only ported over a couple settings, but we can keep adding more.
My current config.nu:
```
filesize_metric: $true
table_mode: with_love
}
```
The `$config` variable follows all the scoping of normal variables and is assumed captured by blocks.
=> Add a config variable with engine support

crates/nu-command/src/core_commands/use_.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-protocol/src/ast/block.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/id.rs
Overlay is no longer attached to a Block.
Makes access to overlays more streamlined by removing this one indirection.
Also makes it easier to create standalone overlays without a block which might come in handy.
This is a precursor to reliable hiding of exported environment variables. The current plan is that in the Stack, the env vars would reference OverlayId they belong to.
=> Separate Overlay into its own thing

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/append.rs, crates/nu-command/src/filters/mod.rs
append a row or rows in a table...
append strings, ints, bools in a list...
reproduce functionality of the nushell append command...
=> port over the append command from nushell

Cargo.lock, Cargo.toml, crates/nu-command/src/core_commands/help.rs, crates/nu-command/src/core_commands/register.rs, crates/nu-command/src/default_context.rs, crates/nu-command/src/example_test.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/Cargo.toml, crates/nu-parser/src/errors.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-plugin/src/plugin.rs, crates/nu-protocol/Cargo.toml, crates/nu-protocol/src/engine/command.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/signature.rs, crates/nu-protocol/src/syntax_shape.rs, crates/nu-protocol/tests/test_signature.rs, src/main.rs
The signatures for the plugins are stored in file `plugin.nu` which are used every time nushell starts. This reduces the loading time since it isnt required to call to each plugin to get its signature
=> Plugins signature load

Cargo.lock, Cargo.toml, crates/nu-ansi-term/.gitignore, crates/nu-ansi-term/Cargo.toml, crates/nu-ansi-term/LICENCE, crates/nu-ansi-term/README.md, crates/nu-ansi-term/examples/256_colors.rs, crates/nu-ansi-term/examples/basic_colors.rs, crates/nu-ansi-term/examples/gradient_colors.rs, crates/nu-ansi-term/examples/rgb_colors.rs, crates/nu-ansi-term/src/ansi.rs, crates/nu-ansi-term/src/debug.rs, crates/nu-ansi-term/src/difference.rs, crates/nu-ansi-term/src/display.rs, crates/nu-ansi-term/src/gradient.rs, crates/nu-ansi-term/src/lib.rs, crates/nu-ansi-term/src/rgb.rs, crates/nu-ansi-term/src/style.rs, crates/nu-ansi-term/src/util.rs, crates/nu-ansi-term/src/windows.rs, crates/nu-ansi-term/src/write.rs, crates/nu-command/Cargo.toml, crates/nu-command/src/viewers/color_config.rs, crates/nu-command/src/viewers/mod.rs, crates/nu-command/src/viewers/table.rs, crates/nu-protocol/src/config.rs, crates/nu-table/Cargo.toml
this is a first pass at allowing some coloring customization. this does coloring and alignment in nearly the same way nushell does. most of the code is ripped off from there. note how the size column is right aligned and the other columns are left aligned.
in order to get something like this, you need to modify your `config.nu` file and include something like this.
```
filesize_metric: $true
table_mode: rounded
use_ls_colors: $true
color_config: {
separator_color: yd
header_color: gb
index_color: gbl
leading_trailing_space_bg: white
header: cb
date: pu
filesize: ub
}
}
```
TBH, i really don't like this coloring code and i'm thinking about changing it, but it's good enough for a first pass.
=> add coloring by primitive, bring in nu-ansi-term crate

crates/nu-command/src/filesystem/ls.rs, crates/nu-command/src/viewers/griddle.rs
* Added proper reading of LS_COLORS environment variable by "ls" command and "griddle" viewer.
* `ls` now displays "symlink" next to symlinks
* Removed a redundant call to `std::fs::symlink_metadata()`.
Another option would be to put `std::env::set_var()/remove_var()` to the Stack helper methods but reading [the docs](https://doc.rust-lang.org/std/env/fn.set_var.html) revealed these std::env calls are not thread-safe and can panic for various reasons, so it's probably better to use our internal env vars whenever possible.
If you imagine calling `let-env` inside a `par-each` block, setting the env vars globally via std::env would create quite a mess, but inside engine-q, we're scoped and thread-safe.
Closes #354 #356 .
=> Fix reading of LS_COLORS + ls displays symlink

crates/nu-command/src/filters/where_.rs, crates/nu-command/src/formats/to/json.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/expression.rs
This allows row conditions to be blocks, and to also carry the row condition as a block instead of an expression. Moved `where` to use this new style.
Also randomly fixed `to json` which wasn't collecting before it was translating to json
=> Move row condition to block

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/all.rs, crates/nu-command/src/filters/mod.rs, crates/nu-protocol/src/pipeline_data.rs, crates/nu-protocol/src/value/from.rs
- Port the `all?` command from nushell
- Implement `From<bool>` for `Value, see 03667f3f.
- Add `PipelineData::into_iterruptible_iter` method, see 498079c9.
- Change `IntoPipelineData` and `IntoInterruptiblePipelineData` bounds to respectively accept `Into<Value>` and `IntoIterator`, see a1fd7077.
```rust
impl<V> IntoPipelineData for V
where
V: Into<Value>,
{
// --snip--
}
impl<I> IntoInterruptiblePipelineData for I
where
I: IntoIterator + Send + 'static,
I::IntoIter: Send + 'static,
<I::IntoIter as Iterator>::Item: Into<Value>,
{
// --snip--
}
```
=> Port `all?` command

src/main.rs
if `EQ_PROMPT_ANIMATION_MS` is set in your environment, such as `export EQ_PROMPT_ANIMATION="5000"`, then your prompt will animate every 5000 ms / 5 seconds. If it is unset then the animation will be set to the default 1000 ms / 1 sec. If it's set to some non-number like "OFF", then the animation will be disabled.
=> enable env setting for prompt animation

crates/nu-command/src/core_commands/hide.rs, crates/nu-command/src/env/with_env.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/import_pattern.rs, crates/nu-protocol/src/engine/stack.rs, src/main.rs, src/tests.rs
This changes environment variables to be arranged in a stack-like structure so that the values can be recovered from the parent scopes. This allows us to implement deactivating overlays.
To detect at eval time whether a parser hid a definition under the same name or not, I kind of hacked the import pattern but I couldn't think of a better way that wouldn't be overly complicated.
=> Hiding of environment variables

Cargo.lock, src/main.rs
Fixes #386
Makes the changes to accept https://github.com/nushell/reedline/pull/188
Change CLI option `EQ_PROMPT_ANIMATE_MS` to binary `EQ_PROMPT_ANIMATE`
=> Fix busy poll with reedline

crates/nu-command/src/viewers/color_config.rs, crates/nu-command/src/viewers/table.rs, crates/nu-table/src/table.rs
add the ability to change the row index color via config with `color_config.row_index`.
note the yellow bold indexes.
My current config.
```
filesize_metric: $true
table_mode: rounded
use_ls_colors: $true
color_config: {
separator: yd
leading_trailing_space_bg: white
header: cb
date: pu
filesize: ub
row_index: yb
bool: red
int: red
duration: red
range: red
float: red
#string: red
nothing: red
binary: red
cellpath: red
}
use_grid_icons: $true
}
```
also, homogenized a coloring key.
=> added row_index coloring

Cargo.lock, crates/nu-command/src/viewers/table.rs, crates/nu-protocol/src/config.rs, crates/nu-table/Cargo.toml, crates/nu-table/src/main.rs, crates/nu-table/src/table.rs, crates/nu-table/src/wrap.rs
This adds the ability to have an optional footer at the end of a table. The footer is a duplicate of the header. It can be configured by placing this in your `config.nu` file.
`  footer_mode: always`
The options are:
```rust
pub enum FooterMode {
/// Never show the footer
Never,
/// Always show the footer
Always,
/// Only show the footer if there are more than RowCount rows
RowCount(u64),
/// Calculate the screen height, calculate row count, if display will be bigger than screen, add the footer
Auto,
}
```
`Auto` is not implemented yet and is just ignored.
=> add optional footer to table

crates/nu-command/src/core_commands/echo.rs, crates/nu-command/src/filesystem/ls.rs, crates/nu-command/src/filters/each.rs, crates/nu-command/src/filters/length.rs, crates/nu-command/src/filters/lines.rs, crates/nu-command/src/filters/par_each.rs, crates/nu-command/src/filters/range.rs, crates/nu-command/src/filters/select.rs, crates/nu-command/src/filters/wrap.rs, crates/nu-command/src/formats/from/eml.rs, crates/nu-command/src/formats/from/ods.rs, crates/nu-command/src/formats/from/url.rs, crates/nu-command/src/formats/from/xlsx.rs, crates/nu-command/src/math/eval.rs, crates/nu-command/src/math/utils.rs, crates/nu-command/src/random/bool.rs, crates/nu-command/src/random/chars.rs, crates/nu-command/src/strings/format/command.rs, crates/nu-command/src/strings/parse.rs, crates/nu-command/src/system/run_external.rs, crates/nu-command/src/viewers/griddle.rs, crates/nu-command/src/viewers/table.rs, crates/nu-plugin/src/plugin.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/pipeline_data.rs, src/main.rs
This adds metadata to `PipelineData`, which is currently only used for `ls`.  This moves the styling of `ls` output to much later (currently `table`)
=> Introduce metadata into the pipeline

crates/nu-command/src/system/run_external.rs, crates/nu-command/src/viewers/table.rs, src/main.rs
This adds table streaming for output, so we don't wait until everything is ready.
This lets the `ls **/*` table stream out.
=> Add table streaming

crates/nu-parser/src/errors.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-protocol/src/ast/import_pattern.rs
* `source` and `use` canonicalize their path which should make them easier to use
* Added file path print to FileNotFound error
=> Add canonicalization to parser paths; Improve FileNotFound error

Cargo.lock, Cargo.toml, src/main.rs
some illbehaved externals turn off `ENABLE_VIRTUAL_TERMINAL_PROCESSING` in windows. This reset that mode.
before:
after:
=> this fixes garbage ansi when externals turn off vt processing

src/main.rs
Update to always try to run `main` if it's visible in the top-level scope.
=> Improve running main

crates/nu-engine/src/eval.rs, crates/nu-protocol/src/value/mod.rs
Provides in-depth info about command signatures, similar to `$nu.lang` in Nushell.
=> Add signature to $scope.commands

Cargo.lock, crates/nu-command/Cargo.toml, crates/nu-command/src/random/integer.rs, crates/nu-command/src/random/mod.rs, crates/nu-command/src/random/uuid.rs, crates/nu-protocol/src/value/mod.rs
Porting integer sub-command in random
Finally! This is the last random command on the porting list.
It is not currently on the porting list, but there is a [uuid](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/commands/random/uuid.rs) in the sub-command of random.
Would it be better to port this too? If it does, it would be fine to do it with this PR because the amount of code is very small.
=> feat(random): add random-integer and random-uuid

crates/nu-command/src/viewers/table.rs, crates/nu-protocol/src/config.rs
with a new config flag you can set the float/decimal precision in tables?
```
float_precision: 2
}
```
```
float_precision: 10
}
```
=> allow decimals/floats to be formatted with precision

Cargo.lock, crates/nu-protocol/src/config.rs, crates/nu-table/Cargo.toml, crates/nu-table/src/table.rs
this is one step toward allowing nushell/engine-q to be configured to not use ansi color output.
With this setting in your `config.nu` file you can remove table coloring.
```
without_color: $true
}
```
note: the `ls` is still colored. we can try to change the command line syntax highlighting in another PR.
`without_color` defaults to `false`
this PR also restored the ability to use detect ttys and use color appropriately. as I recall, one can do `ls` from vim and color is not wanted there.
=> optionally remove table output color

Cargo.lock, crates/nu-protocol/Cargo.toml, crates/nu-protocol/src/config.rs, crates/nu-protocol/src/value/mod.rs, src/tests.rs
this configuaration point allows you to configure the format of the file size listed in tables when you do a `ls` and looks more like nushell's table output.
this setting will automatically determine the display. it defaults to auto
```
filesize_format: "auto"
} 
```
```
filesize_format: "b"
} 
```
note: the number separators are based on your locale
```
filesize_format: "kb"
} 
```
here is the list of available configuration options
```
"b" => byte_unit::ByteUnit::B
"kb" => byte_unit::ByteUnit::KB
"kib" => byte_unit::ByteUnit::KiB
"mb" => byte_unit::ByteUnit::MB
"mib" => byte_unit::ByteUnit::MiB
"gb" => byte_unit::ByteUnit::GB
"gib" => byte_unit::ByteUnit::GiB
"tb" => byte_unit::ByteUnit::TB
"tib" => byte_unit::ByteUnit::TiB
"pb" => …
```
=> Filesize formatting

Cargo.toml
As @fdncred pointed out in my last PR related to the port of `to-md` and `to-html`, the zip support that i added only worked if you did `cargo run --all-features` now it works also if you use `cargo run --features=extra`.
=> Add zip-support to extra

Cargo.lock, crates/nu-command/Cargo.toml, crates/nu-command/src/default_context.rs, crates/nu-command/src/formats/to/mod.rs, crates/nu-command/src/formats/to/xml.rs, crates/nu-command/src/formats/to/yaml.rs
Pretty standard stuff, i don' believe i have anything to talk about besides showing the results. The differences in the cat output and the command output i believe are mostly from the `from` commands. Also the ' converting into `&apos;` seems to also occour in the old engine. probably something to do with the crate that we use. 
```
〉cat ./test.yaml
- martin:
name: Martin D'vloper
job: Developer
skills:
- python
- perl
- pascal
- tabitha:
name: Tabitha Bitumen
job: Developer
skills:
- lisp
- fortran
- erlang
〉cat ./test.yaml | from yaml | to yaml
---
- martin:
skills:
- python
- perl
- pascal
job: Developer
name: "Martin D'vloper"
- tabitha:
job: Developer
skills:
- lisp
- fortran
- erlang
name: Tabitha Bitumen
```
```
〉[1 2 3] | to yaml
---
- 1
- 2
- 3
```
```
〉{ "foo": 1 } | to yaml
--- …
```
=> `to xml` and `to yaml`

Cargo.lock, crates/nu-command/src/core_commands/version.rs
I just think it looks better this way.
=> tweak `version` output as a list vs table

crates/nu-command/src/system/run_external.rs
Now:
```
> ..
```
Will automatically change directories. Auto-cd requires to start with `.`, `/`, or `\`.  The string thing makes this a little awkward for directories with spaces. Might need to think about that a bit (strings would just be an expression in e-q)
=> Add in auto-cd if you pass just a directory

crates/nu-cli/src/completions.rs, crates/nu-command/src/system/run_external.rs
Do better completions when we're working on a filepath that might have quotes and/or spaces.
=> Better filepath completions

crates/nu-command/src/core_commands/hide.rs, crates/nu-parser/src/parse_keywords.rs, docs/Modules_and_Overlays.md, src/tests.rs
Previously, `hide spam *` would hide `spam foo`, `spam bar`, etc. which is identical to `hide spam`.
Now, `hide spam *` will hide `foo`, `bar`, etc. brought in from `spam` with, e.g., `use spam *`. This was impossible with the previous design.
Fixes #445
=> Fix hiding of import patterns with globs

crates/nu-command/src/hash/generic_digest.rs
Example:
```
ls | get name | hash sha256
```
=> Fix error propagation across `hash` commands

crates/nu-parser/src/lex.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/shell_error.rs, src/tests.rs
Fixes these two cases:
```
let x = 10
let x = $x + 9
$x
```
and
```
def foo [] {
let x = 1 + 2 # comment
let y = 3 + 4 # another comment
$x + $y
}
foo
```
=> Fix comment issue and shadowing issue

crates/nu-command/src/default_context.rs, crates/nu-command/src/example_test.rs, crates/nu-command/src/platform/ansi/command.rs, crates/nu-command/src/platform/ansi/mod.rs, crates/nu-command/src/platform/mod.rs
I made a couple of changes - it seems in nushell you could provide an escape, osc, and default value, but only the first one would be actually performed, and the rest ignored. I changes escape and osc to mutually exclusive switches, and changes the optional positional arg to required. I think this was how it was intended to work - but if I am wrong, happy to change it back, just let me know!
I don't have a ton of formal rust experience, so any feedback appreciated.
=> Porting 'ansi' command from nushell to engine-q

crates/nu-command/src/default_context.rs, crates/nu-command/src/example_test.rs, crates/nu-command/src/strings/char_.rs, crates/nu-command/src/strings/mod.rs
Nothing too exciting here. Checked with clippy, ran fmt. Thanks for your patience! #242
=> Porting  'char' command from nushell to engine-q

crates/nu-command/src/platform/ansi/command.rs, crates/nu-command/src/strings/char_.rs
Had to change the name -> code from a match statement to a vector that generates a hashmap, so it can be listed. Since there are a lot of shortcodes, I figured just a hashmap literal would get a little too big. Let me know if you can think of a more elegant solution - I am sure there is one.
I also wasn't sure how I should actually display the code - I just removed the escape character, but could print it as text if you prefer. 
Also added a category to the char command - I missed it in my last commit, figured I would sneak it in.
=> added a 'list' option to the ansi command

src/main.rs
Fixes #505
Q: Are there any other error cases for dialoguer we have to handle separately?
A: Dialoguer returns a `std::io::Error`, thus if we cannot handle stdout anymore the reedline part would fail loudly as well
=> Make dialoguer completion abortable

src/main.rs
Clears to a new line for the potentially hosting process
Remove the output for `Ctrl-C`
=> Fix `Ctrl-D` exit in cli

crates/nu-cli/src/prompt.rs, crates/nu-command/src/core_commands/use_.rs, crates/nu-command/src/default_context.rs, crates/nu-command/src/env/env_command.rs, crates/nu-command/src/env/let_env.rs, crates/nu-command/src/env/mod.rs, crates/nu-command/src/env/with_env.rs, crates/nu-command/src/filesystem/cd.rs, crates/nu-command/src/system/run_external.rs, crates/nu-command/src/viewers/griddle.rs, crates/nu-command/src/viewers/table.rs, crates/nu-engine/src/env.rs, crates/nu-engine/src/eval.rs, crates/nu-engine/src/lib.rs, crates/nu-protocol/src/config.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/engine/stack.rs, crates/nu-protocol/src/shell_error.rs, src/main.rs, src/tests.rs
This PR changes environment variables to be any Value instead of just a String. For example, PATH can be a list:
You can define custom translation from String (captured from host environment) to Value and from Value back to String (to be sent to external command). For example, translation config for PATH can look like this:
```
let config = {
env_conversions: {
"PATH": {
from_string: { |s| $s | split row ':' }
to_string: { |v| $v | str collect ':' }
}
}
}
```
Also, I removed the Nothing value removing the environment variable. If you set an environment variable to Nothing, it will hold this value. If you want to remove it, use `hide`.
For easier inspection and debugging, there is now an `env` command:
=> Treating environment variables as Values

src/main.rs
Makes env vars in the fake startup file wrapped in double quotes so the lexer will parse it correctly. That is, no more splitting of `LS_CHARS` at `;` characters.
=> Fix broken env var reading on startup

crates/nu-plugin/src/plugin/mod.rs, crates/nu-protocol/src/shell_error.rs, crates/nu_plugin_python/plugin.py
Now plugins shell out to cmd or sh only if the file extension is .bat or .sh
An option to shell to python was added, this allows for plugins in python to be developed 
A python plugin example was added. To register the example just use
```
register crates\nu-plugin-python\plugin -e json
```
=> Calling plugin without shell

crates/nu-protocol/src/span.rs
This may not be the right long-term fix, but it at least removes a panic that can happen when you're typing and syntax is incomplete
=> Allow empty span slice for now

crates/nu-engine/src/eval.rs, src/tests.rs
With this, we can finally finish optional param support and check a param for `$nothing` before using it:
```
def foo [x?:int] {
if $x != $nothing {
$x + 10
} else {
5
}
}
foo
```
=> Finish adding support for optional params

crates/nu-command/src/filters/flatten.rs, crates/nu-protocol/src/value/mod.rs, src/main.rs, src/tests.rs
Fixes #533 by opening `flatten` up to treat all lists the same. `flatten` now treats an inner table as a list of rows so that those rows can be flattened into the outer table/list.
=> Flatten should flatten embedded table

crates/nu-command/src/path/expand.rs, crates/nu-protocol/src/shell_error.rs, src/main.rs
If host environment variable contains both ' and ", throw an error.
Also fixed a diagnostic of LabeledError.
=> Fix capturing environment variables with " or '

crates/nu-engine/src/eval.rs
sorted env variables when doing $nu.env
=> sort env vars

crates/nu-cli/src/completions.rs, crates/nu-engine/src/eval.rs, crates/nu-protocol/src/syntax_shape.rs
This does a few improvements to the structured signature:
* skips the `help` flag
* named flags that don't take an arg are now called `switch`
* show the syntax shape instead of the type
* fixed a bug where `rest` was showing up even if the command didn't have one
I also threw in sorting of completions because I was fixing that when I switched tasks :rofl:
=> Signature improvements, sorted completions

crates/nu-parser/src/lib.rs, src/main.rs
When starting engine-q, both the name and the value in the fake file will be put between quotes or double quotes to ensure any weird characters don't break break it. Also, error reporting got cleared up a bit and removed a potential panic.
=> Wrap captured env var names into quotes as well

crates/nu-command/src/system/run_external.rs, crates/nu-engine/src/eval.rs
When you pass a list to an external, it will be treated as a series of arguments for the external:
```
> let l = [ a b c ]
> ^echo "foo" $l
foo a b c
```
=> Interpret lists as series of args for externals

crates/nu-command/src/formats/to/json.rs, crates/nu-json/src/lib.rs, crates/nu-json/src/ser.rs, src/tests.rs
This gives us the ability to get back the json with out the table formatting
in the string...
```rust
[[a b]; [jim susie] [3 4]] | to json -r
```
will produce just the json unformatted...
```rust
[{"a":"jim","b":"susie"},{"a":3,"b":4}]
```
Prior to this addition @fdncred pointed out to me that this
was an alternative solution, which is kind of nice too, but just
a bit more verbose...
```rust
[[a b]; [jim susie] [3 4]] | to json | str find-replace '\n' '' -a | str trim -a
```
=> add in a raw flag in the command to json

crates/nu-protocol/src/config.rs, src/main.rs
allows one to set the maximum size of their history file with this configuration point. max_history_size defaults to 1000.
```
let config = {
max_history_size: 10000
}
```
=> add configuration of maximum history size

crates/nu-color-config/src/color_config.rs, src/main.rs
this pr allows one to change the color of hints. by default hints are dark gray.
```
let config = {
color_config: {
hints: dark_gray
}
}
```
=> add configuration point for hint coloring

crates/nu-engine/src/eval.rs, src/tests/test_engine.rs
Flushes the statements in a block leading up to the last pipeline.
This allows for things like `do { echo 3; echo 4 }` to show both the 3 and 4
=> Flush stmts

crates/nu-command/src/core_commands/history.rs
Reedline currently encodes newlines as `<\n>`
=> Decode escaped newlines in history command

crates/nu-command/src/system/run_external.rs, crates/nu-parser/src/errors.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, src/main.rs, src/tests/test_parser.rs
This PR adds the requirement that `let` is a statement rather than part of a pipeline.
We'll now give an error if you type something like:
```
let x = "hello" | str length
```
As that would visually seem to group the pipeline as part of the right-hand side, but current parsing rules mean that the pipeline gets the precedence, so this wouldn't give the user what they'd assume.
This PR also adds an error message that talks about wrapping the right-hand side in parens in the case where someone writes the above.
It also moves auto-cd to only happen in the CLI and only on a line by itself.
=> Require let to be a statement, move auto-cd

crates/nu-json/src/ser.rs, src/tests/test_converters.rs
Prior to this fix we were removing whitespace from inside the keys and values
as well as outside the keys and values....
Now we NO longer remove whitespace from inside the keys and values,
but instead are leaving them intact....
=> fix issue #559: to json -r serializes datetime without spaces

crates/nu-color-config/src/nu_style.rs, crates/nu-command/src/platform/ansi/command.rs
This adds the ability to specify an ansi style on the command line that will change the foreground, background, and attributes all at the same time.
Added this example to demonstrate.
```rust
Example {
description: "Use ansi to color text with a style",
example: r#"$"(ansi -e { fg: '#0000ff' bg: '#ff0000' attr: b })Hello Nu World(ansi reset)""#,
result: Some(Value::test_string(
"\u{1b}[1;48;2;255;0;0;38;2;0;0;255mHello Nu World\u{1b}[0m",
)),
},
```
=> add ability to specify an ansi style

Cargo.lock, src/main.rs
If there is no history file, e-q never creates one and the history is not stored
=> create history file if it doesnt exit

crates/nu-protocol/src/value/mod.rs, src/tests/test_table_operations.rs
The `update` command will also now perform an insert operation for records/tables.
eg)
```
ls | update foo bar
```
Will add a new foo column, defaulting to bar as the cell value
=> Allow update to also insert

crates/nu-engine/src/eval.rs
When checking if we need to output to the screen, we had accidentally been checking the config at each loop step as it was the first step of `eval_block`. Instead, check the config closer to where the output will actually happen so we only pay for the lookup when we're already going to pay for an i/o.
=> Don't read config in a tight loop

src/main.rs
If the config directory does not exist and `reedline` can't save history, so <kbd>ctrl</kbd> + <kbd>n</kbd> or <kbd>ctrl</kbd> + <kbd>p</kbd> will not work.
=> Create config directory if it does not exist

crates/nu-cli/src/prompt.rs, src/main.rs
This is supposed to allow prompt indicators to be configurable.
You should be able to set these env vars in your config.nu and e-q applies them.
```
let-env PROMPT_INDICATOR = "A "
let-env PROMPT_INDICATOR_VI_INSERT = "I "
let-env PROMPT_INDICATOR_VI_VISUAL = "V "
let-env PROMPT_MULTILINE_INDICATOR = "- "
```
=> make prompt indicators configurable

crates/nu-command/src/filters/get.rs, src/tests/test_table_operations.rs
lets you ignore (and return `$nothing`) when a cell path doesn't match what `get` is working with.
eg) this would return `$nothing`
```
> ls | get -i asdfasdf
```
=> Add fuzzy/ignore flag to get

crates/nu-parser/src/lite_parse.rs, src/tests/test_parser.rs
this now works:
```
do {
ls |
get name
}
```
=> Allow pipelines across multiple lines if end in pipe

crates/nu-parser/src/parse_keywords.rs
so you can do something like `source "c:\some\path\to\a\file.nu"`
=> tweak `source` parsing to allow quotes around string

crates/nu-command/src/default_context.rs, crates/nu-command/src/shells/enter.rs, crates/nu-command/src/shells/exit.rs, crates/nu-command/src/shells/g.rs, crates/nu-command/src/shells/mod.rs, crates/nu-command/src/shells/n.rs, crates/nu-command/src/shells/p.rs, crates/nu-command/src/shells/shells_.rs, src/main.rs
Adds supports for nushell-style shells, and includes all the shells commands (n, p, g, shells, and enter) as well as extending exit to support shells.
Also fixes #670
=> Add shells support

crates/nu-command/src/filters/each.rs
Now that `PWD` is an env var, it's important that we're always seeing a fresh env each time through the loop, or we might accidentally reuse the cwd of the previous iteration.
=> Each needs to clone its env

crates/nu-command/src/filesystem/cd.rs, crates/nu-command/src/filters/each.rs, crates/nu-protocol/src/engine/stack.rs, crates/nu-protocol/src/shell_error.rs
The environment is cloned only if it has changed on the stack. If it hasn't changed (i.e., the stack is empty), no cloning is necessary. This prevents unnecessary cloning of the empty data structures as long as you don't modify the env vars in a tight loop.
This loop works now:
```
ls | where type == dir | each { cd $it.name; ls } | flatten
```
Also fixes how canonicalize error is displayed and a potential std::env creep in the `cd` command.
=> Fixes how environment is cloned inside tight loops

crates/nu-engine/src/eval.rs, src/tests/test_engine.rs
This allows you to check for missing named params, like so:
```
def foo [--aaa(-a): int, --bbb(-b): int] {
(if $aaa == $nothing { 10 } else { $aaa }) + (if $bbb == $nothing { 100 } else { $bbb })
}
foo -b 45
```
=> Default the values of named params

crates/nu_plugin_gstat/src/gstat.rs
Adds `repo_name` and `tag` fields to `gstat` output.
Example output:
```
╭─────────────────────┬────────────────────────╮
│ idx_added_staged    │ 0                      │
│ idx_modified_staged │ 0                      │
│ idx_deleted_staged  │ 0                      │
│ idx_renamed         │ 0                      │
│ idx_type_changed    │ 0                      │
│ wt_untracked        │ 19                     │
│ wt_modified         │ 1                      │
│ wt_deleted          │ 0                      │
│ wt_type_changed     │ 0                      │
│ wt_renamed          │ 0                      │
│ ignored             │ 0                      │
│ conflicts           │ 0                      │
│ ahead               │ 0                      │
│ behind              │ 0 …
```
=> Add repository name and current tag to gstat

crates/nu-command/src/strings/char_.rs
added a few more chars to help with prompt construction
```rust
"nf-branch" => '\u{e0a0}'.to_string(),                     // 
"nf-segment" => '\u{e0b0}'.to_string(),                    // 
"nf-left-segment" => '\u{e0b0}'.to_string(),               // 
"nf-left-segment-thin" => '\u{e0b1}'.to_string(),          // 
"nf-right-segment" => '\u{e0b2}'.to_string(),              // 
"nf-right-segment-thin" => '\u{e0b3}'.to_string(),         // 
"nf-git" => '\u{f1d3}'.to_string(),                        // 
"nf-git-branch" => "\u{e709}\u{e0a0}".to_string(),         // 
"nf-folder1" => '\u{f07c}'.to_string(),                    // 
"nf-folder2" => '\u{f115}'.to_string(),                    // 
"nf-house1" => '\u{f015}'.to_string(),                     // 
"nf-house2" => …
```
=> add more chars

crates/nu-command/src/conversions/fmt.rs, crates/nu-command/src/conversions/mod.rs, crates/nu-command/src/default_context.rs
command to convert numbers to other formats
then it's easy to extract one format from the record
I considered passing a requested format as a parameter and I think it's easier just to return all of them and pick the one you want.
=> new command `fmt` to format numbers

crates/nu-table/src/wrap.rs
this is another round of testing to try to get a little better table column alignment. this is tested with the emoji json in the nu_scripts/assets folder.
before
after
=> a little better table alignment

README.md
Prompted by a question on discord we might want to add infos for those not fully versed in the Rust ecosystem
=> Add instructions to run engine-q

crates/nu-parser/src/errors.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, src/tests/test_engine.rs, src/tests/test_parser.rs
Makes special cases for expression forms that are calling known nushell keywords. This fixes a bug where you couldn't use `for` in a pipeline, as the variable capture wouldn't work correctly.
We'll now also give an error if a statement is used in a pipeline
=> Improve keyword parsing, including for

Cargo.lock, crates/nu-command/src/system/ps.rs
Hide the `status` column for `ps` on Windows until we can come up with a good way to get it.
Also bump reedline
=> Hide Windows ps status, bump reedline

crates/nu-parser/src/type_check.rs
This PR fixes #699
The equality operators now return
```rust
(Type::Bool, None),
```
so everything is allowed to be compared now. Which also fixes boolean inequality.
While looking for this fix I found out that lots of code in operator type check is just replicated. I don't have much context but it looks like we can reduce duplication and avoid problems like being able to compare bools using `==` but not `!=`.
Also is there any reason why `Operator::Equal` doesn't have `(Type::Int, Type::Int)` and `(Type::Float, Type::Float)` patterns but `Operator::NotEqual` has them?
=> Fix not equal returning error when same things are compared in some cases

crates/nu-command/src/viewers/table.rs
Types like floats weren't getting formatted properly in lists. It should've been respecting the `float_precision: x` in the config.nu file.
Example: broken
```
> seq 1.0 0.1 2.0 
╭────┬────────────────────╮
│  0 │ 1                  │
│  1 │ 1.1                │
│  2 │ 1.2                │
│  3 │ 1.3                │
│  4 │ 1.4                │
│  5 │ 1.5                │
│  6 │ 1.6                │
│  7 │ 1.7000000000000002 │
│  8 │ 1.8                │
│  9 │ 1.9                │
│ 10 │ 2                  │
╰────┴────────────────────╯
```
Example: fixed, where `float_precision: 2` is set in config.nu
```
> seq 1.0 0.1 2.0 
╭────┬──────╮
│  0 │ 1.00 │
│  1 │ 1.10 │
│  2 │ 1.20 │
│  3 │ 1.30 │
│  4 │ 1.40 │
│  5 │ 1.50 │
│  6 │ 1.60 │
│  7 │ 1.70 │
│  8 │ 1.80 │
│  9 │ 1.90 │
│ 10 │ 2.00 …
```
=> fix list formatting

crates/nu-table/src/wrap.rs
Ansi-cut expects ranges of character numbers (of the non-ansi control
sequence characters) instead of byte indices.
This fixes the panics when wrapping of non-ASCII lines (which exceed
the demanded number of characters as byte indices).
Also rectifies some wrong wrapping of unicode containing lines that
don't panic
=> Fix unicode word wrapping with ansi-cut

crates/nu-protocol/src/value/mod.rs
This allows the `size` command, to be able to count binary bytes by converting it with `as_string()` and then counting as it does already. This may be the wrong place to do this, so I'm open to suggestions.
=> allow `size` and other to count bytes from binary with `as_string()`

crates/nu-command/src/conversions/into/string.rs, crates/nu-command/src/formats/to/md.rs, crates/nu-protocol/src/config.rs, crates/nu-protocol/src/value/mod.rs, src/reedline_config.rs, src/repl.rs
A more general approach to the keybindings definition
It can define a keybinding that has one or multiple events
Example
```
keybindings: [
{
name: completition
modifier: CONTROL
keycode: Char_t
mode: vi_insert # emacs vi_normal vi_insert
event: {
send: ContextMenu
}
}
{
name: prev_shell
modifier: CONTROL
keycode: Char_y
mode: vi_insert
event: [
{
edit: { cmd: Clear}
}
{
edit: { cmd: InsertChar value: p}
}
{
send: Enter
}
]
}
{
name: next_shell
modifier: CONTROL
keycode: Char_u
mode: vi_insert
event: [
{
edit: { cmd: Clear}
}
{
edit: { cmd: InsertChar value: n}
}
{
send: Enter
}
]
}
]
```
=> general keybindings

crates/nu-protocol/src/config.rs
This is more of a stop-gap fix, but this allows us to be more resilient if the config has a few issues in it.
Should also fix #774
=> Show error on bad config, but keep going

crates/nu-cli/Cargo.toml, crates/nu-color-config/Cargo.toml, crates/nu-command/Cargo.toml, crates/nu-engine/Cargo.toml, crates/nu-json/Cargo.toml, crates/nu-parser/Cargo.toml, crates/nu-path/Cargo.toml, crates/nu-plugin/Cargo.toml, crates/nu-pretty-hex/Cargo.toml, crates/nu-protocol/Cargo.toml, crates/nu-table/Cargo.toml, crates/nu-term-grid/Cargo.toml, crates/nu_plugin_example/Cargo.toml, crates/nu_plugin_gstat/Cargo.toml, crates/nu_plugin_inc/Cargo.toml
it looks like on my local machine that the 2021 edition for all cargo crates is working....
=> update all cargo crates to edition 2021

crates/nu-cli/src/completions.rs
we used to have to check `Path` on Windows and `PATH` on linux/mac. It appears that we now can just check `PATH`, yay!
=> `PATH` for completions for each os

crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, src/tests/test_parser.rs
This fixes an issue when doing variable captures, where we'd capture recursively if functions were recursive (or mutually recursive). This avoids recalculating functions already in-progress to be calculated.
fixes #795
=> Support recursive functions in capture

crates/nu-command/src/network/fetch.rs
I am surprised the CI `cargo fmt --all -- --check` did not catch this.
=> lint: remove trailing whitespace

crates/nu-parser/src/lite_parse.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-parser/tests/test_lite_parser.rs, src/tests.rs, src/tests/test_parser.rs
This allows you to put doc comments onto custom commands, like:
```
#
def hello-world [] { echo "I say hello here" }
```
=> Fix doc comments for custom commands

crates/nu-table/Cargo.toml, crates/nu-table/src/wrap.rs
Hi there,
After overseeing #767.
I noticed an issue in `ansi-cut`.
If color was used like this `"\u{1b}[41m\u{1b}[30msomething\u{1b}[39m \u{1b}[34m123123\u{1b}[39m\u{1b}[49m"`
(A color was closed not each time it is used) we did not recognize that, therefore the colors could be screwed.
I did a fix so it must be handled right now.
And I am here point out about the issue and to bring the fix.
But doing the bump.
I did not found any tests.
Do you have any?
As it's not quite safe to make just a bump because now `ansi-cut` `panic`s when you index not a UTF-8 code point boundary (it uses byte indexing now as well)
____
I did not inspect deliberately these lines, just have a little concern that `word.cut(start_index..end_index+width)` must be used here? …
=> draft: Bump `ansi-cut` version to 0.2.0

Cargo.lock, crates/nu-command/src/default_context.rs, crates/nu-command/src/platform/input_keys.rs, crates/nu-command/src/platform/mod.rs
<kbd>option</kbd> + <kbd>delete</kbd>
<kbd>control</kbd> + <kdb>d</kbd>
I can only capture one key event. Do you think we can make this loop somehow?
/cc @jntrnr 
Update: couldn't get nushell tables to work but got a raw mode to work.
=> capture keyboard event

crates/nu-command/src/filters/sort_by.rs, crates/nu-engine/src/column.rs
**_sort-by_** is crashing engine-q under certain input sequences...
this hopefully fixes everything except for the case of types.
that will be addressed next after this lands.
this PR fixes the following cases
* ls | sort-by
* ls | sort-by unknown-column
* ls | sort-by unknown-column known-column
* ls | sort-by known-column unknown-column
=> fix several cases where sort-by was crashing engine-q

crates/nu-command/src/filesystem/open.rs, crates/nu-protocol/src/value/mod.rs
Allow `open` to read the filename it uses for input from the pipeline.
=> Allow `open` to read its filename from input

crates/nu-protocol/src/value/mod.rs, src/tests/test_engine.rs
Fixes a bug in date comparison where we were comparison for a new day rather than any change to the datetime.
=> Fix bug in date comparison

crates/nu-command/src/filters/flatten.rs
Flatten records when calling `flatten`. Closes #828
=> Flatten records

crates/nu-command/src/system/run_external.rs
Fixes #844. Recent support for globs accidentally removed path expansion on external args. This should add back what we had previously.
=> Fix expanding external args

crates/nu-command/src/default_context.rs, crates/nu-command/src/system/exec.rs, crates/nu-command/src/system/mod.rs, crates/nu-command/src/system/run_external.rs
This is a port of the `exec` command, though mostly it's a rebuild as it builds from the new logic in `run_external` rather than using the nushell logic. This should (hopefully) allow for things like file expansion, glob expansion, etc.
=> Port exec command

crates/nu-engine/src/documentation.rs, crates/nu-parser/src/lib.rs, src/commands.rs, src/main.rs, src/repl.rs, src/tests/test_engine.rs
This adds a few more commandline flags to the nu binary:
* -l/--login - make this a login shell
* -i/--interactive - make it an interactive shell
* -c/--commands - run some commands, then exit
I also tweaked some of the help formatting to be a little nicer, namely flag descriptions now follow flags, and have an indentation.
=> Add -c flag and others to cmdline args

crates/nu-command/src/filters/sort_by.rs
Add support for Date and Filesize comparison for `sort-by` command - see  #818
Closes #843
=> Add suport for Filesize and Date for sort-by command

crates/nu-parser/src/parser.rs, src/tests/test_parser.rs
You can now use `=` to separate a long flag from its argument, like so:
```
> seq 1 4 --separator='+'
```
=> Allow equals to separate long flag and arg

Cargo.lock, crates/nu-cli/src/prompt.rs, src/prompt_update.rs, src/reedline_config.rs, src/repl.rs
Improvements to menus
- history menu is activated with ctr+i
- history search is not limited to one page
- menus markers can be changed in config file
Extra changes
- Removed unused visual mode
- Indicator for normal mode in vi
=> using menu trait

crates/nu-command/src/conversions/into/datetime.rs
the into  datetime's offset should be Int instead of string 
=> Fix into datetime example parameter type

src/reedline_config.rs
Moves history search to ctrl-x
=> Move history search to ctrl-x

crates/nu-cli/src/syntax_highlight.rs
Hardens the syntax highlighter against spans that come from aliases (which are in a different part of source than is currently highlighted). For now, this will result in them being highlighted white.
Fixes #859 
Fixes #770 
Fixes #771 
=> Harden highlighter against alias spans

src/reedline_config.rs
As we are short on keybinding options support the F\d-keys as well
=> Add F1-F12 key support

Cargo.lock
Should remove the need for manual `str find-replace -a (char newline) (char crlf)` in `PROMPT_COMMAND`
Fixes #575
(description of your pull request here)
=> Bump reedline

crates/nu-system/src/macos.rs
=> fixes process path being truncated

src/tests/test_table_operations.rs
This test shows that we now have the ability to test
tables with multiple columns using
json -r in concert with rustfmt::skip
close #432 
```rust
#[test]
#[rustfmt::skip]
fn command_filter_reject_4() -> TestResult {
run_test(
"[[lang, gems, grade]; [nu, 100, a]] | reject gems | to json -r",
r#"[{"lang": "nu","grade": "a"}]"#,
)
}
```
=> add in a table test with multiple columns

crates/nu-command/src/core_commands/help.rs
This lets everyone know when they type the help command that
```rust
help --find <text to search>
```
is a very valuable way to search through all of help.
I can never remember this myself so I thought other users would
want to know about it too.
=> add help --find to help doc

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/rename.rs, crates/nu-command/src/strings/detect_columns.rs, crates/nu-command/src/strings/mod.rs
This is a port of Nushell's `detect columns` functionality, with some bug fixes.
=> Port `detect columns`

crates/nu-command/src/filters/lines.rs, crates/nu-command/src/strings/detect_columns.rs
Silence the erroneous clippy warnings about collecting.
cc @stormasm who was asking about this
=> Ignore clippy's erroneous warnings

crates/nu-command/src/default_context.rs, crates/nu-command/src/experimental/mod.rs, crates/nu-command/src/experimental/view.rs, crates/nu-command/src/experimental/view_source.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/block.rs, crates/nu-protocol/src/overlay.rs
This PR adds an experimental `view` command that lets you view the source code of:
* a block 
* a module
* a custom command
* Currently, viewing individual blocks of `export env` is not possible -- you need to view the whole module. However, viewing `export def` and `export def-env` is possible (e.g., using `view "module-name def-name").
* It shows only the block part. E.g., the `def name [args...]` parts will be lost.
=> Allow viewing the source code of blocks

crates/nu-command/src/system/run_external.rs, crates/nu-protocol/src/engine/stack.rs, crates/nu-protocol/src/pipeline_data.rs
This switches from outputting debug text to translating structured data via `table` (without color) when sending between an internal command and an external command.
Things this allows you to do:
```
> ls | less
```
```
> ls | grep darren
│  6 │ darren.nu        │ file │     154 B │ 3 weeks ago  │
│ 13 │ source_darren.nu │ file │      50 B │ 2 weeks ago  │
```
And so on.
In short, it helps play a little nicer at the boundary if people just want to fall back onto their current toolset with what they're looking at on the screen.
=> Use 'table' during internal->external

crates/nu-command/src/conversions/into/datetime.rs
```
> into datetime --list                                       
╭──────┬─────────────────────────────────────────────────────────────────────────────────────────╮
│ code │ Description                                                                             │
│ %F   │ Year-month-day format. Same to %Y                                                       │
│ %Y   │ The full proleptic Gregorian year, zero-padded to 4 digits(Example: 2001).              │
│ %C   │ The proleptic Gregorian year divided by 100, zero-padded to 2 digits. (Example: 20)     │
│ %y   │ The proleptic Gregorian year modulo 100, zero-padded to 2 digits. (Example: 01)         │
│ %m   │ Month number (01--12), zero-padded to 2 digits.(Example: 07)                            │
│ %b   │ Abbreviated month name. Always …
```
=> Add strftime cheatsheet for `into datetime` (#869)

crates/nu-command/src/system/run_external.rs, src/tests.rs, src/tests/test_hiding.rs
Attempt to spawn as normal in Windows, but if that fails, now also fallback to calling through cmd and see if that helps.
Removes the `\\\\` regex as well.
=> Add a fallback if Windows external spawn fails

crates/nu-command/src/date/format.rs, crates/nu-command/src/random/integer.rs
fixes #903 
`gen_range(min..max)` was supposed to be `gen_range(min..=max)`
=> should be inclusive

Cargo.lock
- Keybinding related improvements
- internals
- Vi insert should know more keybindings
=> Obligatory reedline bump

docs/How_To_Coloring_and_Theming.md
updated some theming points with color and style defaults. removed decode uff-8.
=> added defaults for colors

Cargo.lock, src/reedline_config.rs
- Pasting text containing multiple newline separated commands will now return each command (considered valid based on `Validator`) for evaluation and parse the paste after the next invocation of `Reedline::read_line`
=> Update reedline to paste multiple command lines

Cargo.lock, Cargo.toml, crates/nu-cli/Cargo.toml, crates/nu-protocol/src/config.rs, src/repl.rs
This adds support to enable (off by default) a completion mode that will auto-select the completion if you type and reach the point of having a single entry.
To configure this setting, use `$config.quick_completions`, a bool
=> Add support for quick completions

crates/nu-engine/src/eval.rs, crates/nu-protocol/src/engine/stack.rs, src/tests/test_engine.rs
Fixes https://github.com/nushell/engine-q/issues/907
```
> let-env FOO = "foo"
> def-env hide-foo [] {
hide FOO
}
> $env.FOO
```
=> Allow def-env to hide environment variables

crates/nu-command/src/conversions/into/filesize.rs, crates/nu-command/tests/commands/into_filesize.rs
fix `into filesize` and it's tests
=> fix into filesize tests and filesize

crates/nu-command/src/core_commands/describe.rs
This will do a collect on the pipelinedata, converting it into a Value, before doing the describe step. This gives us a bit more useful info on the input.
=> Simplify `describe`

crates/nu-command/src/filesystem/ls.rs, crates/nu-command/tests/commands/ls.rs
had to change how `ls` works a tiny bit. when there's nothing in the glob it will now report 'no matches found'.
=> fix `ls` and ls tests

crates/nu-command/src/env/let_env.rs, src/tests/test_engine.rs
=> Allow let-env to be dynamic

crates/nu-command/tests/commands/math/avg.rs
This fixes the test **can_average_bytes**
in the file math/avg.rs
=> fix test math/avg.rs can_average_bytes

crates/nu-command/src/core_commands/error_make.rs
Remove broken `error make` examples. These were ported from nushell, but these spans need to be valid spans for this to work, and you can't create valid spans yourself (you need to use helpers like `metadata`).
=> Remove broken error make examples

Cargo.lock
The text file based history will not have a race condition if multiple sessions try to access the history file and are forced to truncate due to capacity
=> Update reedline to race-condition-free history

crates/nu-command/src/core_commands/for_.rs, crates/nu-command/src/filters/each.rs, crates/nu-command/src/filters/each_group.rs, crates/nu-command/src/filters/par_each.rs, crates/nu-command/src/filters/where_.rs, crates/nu-engine/src/eval.rs, crates/nu-engine/src/lib.rs
This moves commands like `for`, `each`, `each group`, and `par-each` to use redirecting block evaluation, so that externals that end the block have their output redirected.
=> Switch more commands to redirecting blocks

crates/nu-command/src/filters/each_group.rs, crates/nu-command/src/filters/each_window.rs, crates/nu-command/src/filters/par_each_group.rs, crates/nu-command/tests/commands/each.rs
Oops, made a couple mistakes in the semantics of `each group` and `each window`. Fixed. Enabled nushell tests.
=> Oops, match semantics of each group/window
