src/lex.rs, src/lite_parse.rs, src/main.rs, src/parser.rs, src/parser_state.rs, src/span.rs
Reverts jonathandturner/engine-q#1
=> Revert "Removed file_id in Span, compact file sources"

src/lex.rs, src/lite_parse.rs, src/main.rs, src/parser.rs, src/parser_state.rs, src/span.rs
Reverts jonathandturner/engine-q#2
=> Revert "Revert "Removed file_id in Span, compact file sources""

.github/workflows/ci.yml, crates/nu-protocol/src/signature.rs, crates/nu-protocol/tests/test_signature.rs
=> Similar name check to protocol

TODO.md, crates/nu-cli/src/errors.rs, crates/nu-command/src/each.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/block.rs, crates/nu-protocol/src/engine/command.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/signature.rs, crates/nu-protocol/src/ty.rs, crates/nu-protocol/src/value.rs, src/tests.rs
This adds block params and implicit block params:
```
[2] | each { |x| $x + 10 }
```
```
[3] | each { $it + 100 }
```
=> Block params

crates/nu-cli/src/errors.rs, crates/nu-command/src/each.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/value.rs, src/tests.rs
This moves `each` to always working on outputting as an iteration. Not done yet, but this adds range iteration and list iteration.
=> Range iteration

src/tests.rs
simple build-string tests along with simple string iteration
=> some build-string tests

TODO.md, crates/nu-cli/src/completions.rs, crates/nu-cli/src/lib.rs, crates/nu-command/src/default_context.rs, crates/nu-command/src/if_.rs, crates/nu-command/src/lib.rs, crates/nu-command/src/where_.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/value/mod.rs, src/main.rs, src/tests.rs
This adds simple completions for command names and support for row conditions (the expression type that commands like `where` use).
I've added a simple `where` implementation in so we can ensure that this works.
=> Completions and Row Conditions

crates/nu-cli/src/errors.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/block.rs
Parsing no longer panics with def, let and alias
=> Parse errors for def, let and alias

crates/nu-parser/tests/test_parser.rs, crates/nu-protocol/src/value/range.rs
This PR adds support for floating point numbers to the ranges.
=> Floating point ranges

src/tests.rs
added some more tests around the idea of block params in concert with list iteration
added some more build-string tests using lists
=> more block param and build string tests in concert with lists

crates/nu-cli/src/errors.rs, crates/nu-parser/src/errors.rs, crates/nu-parser/src/parser.rs
highlighting for alias and let when missing name or equal sign
=> Error check on def and alias

crates/nu-parser/src/lex.rs
=> Fix issue with unexpected EOF rendering in miette

Cargo.lock, Cargo.toml, crates/nu-cli/Cargo.toml, crates/nu-parser/Cargo.toml, crates/nu-protocol/Cargo.toml, crates/nu-protocol/src/engine/engine_state.rs
=> Fix multifile miette crash

crates/nu-command/src/table.rs
=> Revert "improve table for lists"

Cargo.lock, crates/nu-command/src/core_commands/help.rs, crates/nu-command/src/core_commands/mod.rs, crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/for_.rs, crates/nu-command/src/system/mod.rs, crates/nu-command/src/system/ps.rs, crates/nu-command/src/system/sys.rs, crates/nu-engine/Cargo.toml, crates/nu-engine/src/call_ext.rs, crates/nu-engine/src/from_value.rs, crates/nu-engine/src/lib.rs, crates/nu-protocol/src/ast/call.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/engine/evaluation_context.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/span.rs, crates/nu-protocol/src/value/mod.rs
This adds the `ps` command and a very early version of `help`.
=> add ps and early help

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/mod.rs, crates/nu-command/src/filters/select.rs, crates/nu-protocol/src/ast/cell_path.rs, crates/nu-protocol/src/value/mod.rs, src/tests.rs
Add the `select` command (simplified)
=> Add select

crates/nu-command/src/filters/first.rs
Add back binary support for the first command. I have not tested it as I am not sure how :-) Suggestions are welcomed.
=> Add back binary support for the first command

crates/nu-parser/src/parser.rs, src/tests.rs
Fixes https://github.com/nushell/engine-q/issues/297
=> Fix precedence parse

crates/nu-plugin/schema/plugin.capnp, crates/nu-plugin/src/plugin.rs, crates/nu-plugin/src/plugin_call.rs, crates/nu-plugin/src/plugin_capnp.rs, crates/nu-plugin/src/serializers/call.rs, crates/nu-plugin/src/serializers/signature.rs, crates/nu-plugin/src/serializers/value.rs
Small changes to schema to make it more efficient
=> capnp proto change schema

crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expression.rs, src/tests.rs
=> Add magic $in variable, part 2

Cargo.lock, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, src/tests.rs
=> Fix multiword imports/exports

crates/nu-command/src/default_context.rs, crates/nu-command/src/strings/mod.rs, crates/nu-command/src/strings/parse.rs
I'm not exactly sure I did the right thing with spans and errors. Also, am I right with the list of records? This looks like a lot of duplicated information.
=> Port parse command

TODO.md, crates/nu-command/src/viewers/table.rs
Do a similar calculation for width to what we do in nushell
=> Fix term width for the table

Cargo.lock, crates/nu-parser/Cargo.toml, crates/nu-parser/src/parser.rs
=> Expand globs and filepaths

crates/nu-parser/src/lex.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-parser/tests/test_lex.rs, crates/nu-parser/tests/test_lite_parser.rs, src/tests.rs
=> Add better comment skipping

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/drop/command.rs, crates/nu-command/src/filters/drop/mod.rs, crates/nu-command/src/filters/mod.rs
reproduce the functionality of the nushell drop command...
once this PR lands then I will start working on the....
**subcommands**
drop column
drop nth
=> port over the drop command from nushell

crates/nu-command/src/random/chars.rs, crates/nu-command/src/random/mod.rs
Porting chars sub-command in random
=> feat(random): add random-chars

crates/nu-parser/src/parse_keywords.rs, crates/nu-protocol/src/engine/engine_state.rs
To reflect better what the method actually does.
=> Rename add_decls() to use_decls()

crates/nu-command/src/default_context.rs, crates/nu-command/src/strings/str_/mod.rs, crates/nu-command/src/strings/str_/trim/command.rs, crates/nu-command/src/strings/str_/trim/mod.rs
Larger PR due to many test cases. Feedback is welcomed!
=> Port str trim

crates/nu-command/src/core_commands/debug.rs, crates/nu-command/src/viewers/color_config.rs, crates/nu-command/src/viewers/table.rs, crates/nu-protocol/src/value/mod.rs
=> add back debug --raw switch

crates/nu-command/src/random/decimal.rs, crates/nu-command/src/random/mod.rs, crates/nu-protocol/src/shell_error.rs, crates/nu-protocol/src/value/mod.rs
Porting decimal sub-command in random
Perhaps, there might be a better way? Please let me know if you have any!
=> feat(random): add random-decimal

crates/nu-command/src/conversions/into/int.rs
@fdncred, @kubouch 
this PR adds the `str to-int` support for the `into int` command. Let me know if you have any feedback.
=> Add the support of str to-int to the into int command

crates/nu-command/src/viewers/table.rs, crates/nu-protocol/src/value/mod.rs
This should simplify the printing of tables to closer to what nushell does
=> Add value abbreviations

crates/nu-command/src/core_commands/hide.rs, crates/nu-command/src/core_commands/use_.rs, crates/nu-command/src/filters/all.rs, crates/nu-command/src/filters/any.rs, crates/nu-command/src/filters/skip/command.rs, crates/nu-command/src/filters/skip/until.rs, crates/nu-command/src/filters/skip/while_.rs, crates/nu-command/src/filters/where_.rs, crates/nu-command/src/strings/parse.rs, crates/nu-command/src/strings/size.rs, crates/nu-command/src/strings/split/chars.rs, crates/nu-command/src/strings/split/column.rs, crates/nu-command/src/strings/split/row.rs, crates/nu-plugin/src/plugin.rs, crates/nu-plugin/src/plugin_call.rs, crates/nu-plugin/src/serializers/call.rs, crates/nu-plugin/src/serializers/signature.rs, crates/nu-plugin/src/serializers/value.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/engine/stack.rs, crates/nu-protocol/src/shell_error.rs, crates/nu_plugin_example/src/main.rs, crates/nu_plugin_inc/src/inc.rs, crates/nu_plugin_inc/src/nu/mod.rs
InternalError is basically the equivalent of an ICE for compilers. I've renamed it to make it more obvious it's some internal things breaking and moved the errors over to something a little better.
=> Just a few cleanups around error messages

crates/nu-command/src/core_commands/help.rs, crates/nu-engine/src/documentation.rs, crates/nu-engine/src/eval.rs, crates/nu-protocol/src/engine/engine_state.rs
* `help commands` wasn't getting the newest version of a command signature, that's now fixed
* Added `is_custom` column to `help commands` and `$scope.commands`
* Added custom commands to `help commands`
=> Fix 'help commands'; Add 'is_custom' column

src/main.rs
=> Fix the failure if the prompt breaks

crates/nu-command/src/random/dice.rs, crates/nu-command/src/random/mod.rs
Porting dice sub-command in random
=> feat(random): add random-dice

crates/nu-engine/src/eval.rs
=> add `home-path` to `$nu`

crates/nu-engine/src/eval.rs
=> add `keybinding-path` to `$nu`

crates/nu-engine/src/eval.rs
=> add `cwd` to `$nu`

crates/nu-engine/src/eval.rs
=> Add `temp-path` to `$nu`

crates/nu-command/src/default_context.rs, crates/nu-command/src/random/mod.rs
=> Fix: add missing bind commands

Cargo.lock, crates/nu-command/Cargo.toml, crates/nu-command/src/system/ps.rs
=> Seems ps still needs a delay to be accurate

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/drop/column.rs, crates/nu-command/src/filters/drop/mod.rs, src/tests.rs
=> port over from nushell drop column

crates/nu-command/src/default_context.rs, crates/nu-command/src/filters/drop/mod.rs, crates/nu-command/src/filters/drop/nth.rs
=> port over from nushell drop nth

crates/nu-command/src/default_context.rs, crates/nu-command/src/platform/ansi/gradient.rs, crates/nu-command/src/platform/ansi/mod.rs, crates/nu-command/src/platform/mod.rs
Should be pretty much as it was in nushell, let me know if you have any feedback or questions! Work on #242
=> Porting  'ansi gradient' command from nushell to engine-q

crates/nu-command/src/default_context.rs, crates/nu-command/src/example_test.rs, crates/nu-command/src/platform/ansi/mod.rs, crates/nu-command/src/platform/ansi/strip.rs, crates/nu-command/src/platform/mod.rs
Pretty straightforward - same as ansi gradient.  Work on #242
=> Port 'ansi strip' command from nushell to engine-q

crates/nu-command/src/core_commands/register.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-plugin/src/plugin/declaration.rs, crates/nu-plugin/src/plugin/mod.rs, crates/nu-protocol/src/engine/command.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/shell_error.rs, crates/nu_plugin_python/plugin.py
option to register a shell by indicating what shell can be used to call the plugin
```
register crates\nu_plugin_python\plugin.py -e json -s c:\Users\One\AppData\Local\Programs\Python\Python38\python.exe
```
=> Plugin option for shell

crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs
Fix crash when doing `register<tab>` or `source<tab>`
=> Fix completion crash

crates/nu-command/src/formats/to/xml.rs, crates/nu-command/src/viewers/table.rs, crates/nu-protocol/src/value/mod.rs
Merge heterogeneous rows into merged heterogeneous tables. These will have markers in cells that are missing for that row, but otherwise will show as one large table.
fixes #535
=> Merged heterogeneous tables

crates/nu-command/src/viewers/table.rs
fix https://github.com/nushell/engine-q/issues/539
=> Fix list printing

crates/nu-command/src/filters/lines.rs, src/tests.rs
=> Add skip-empty flag to lines command

Cargo.lock
This should fix multiline paste newlines and some of the crashes for large pastes.
=> Some multiline fixes

crates/nu-command/src/default_context.rs, crates/nu-command/src/example_test.rs, crates/nu-command/src/filters/compact.rs, crates/nu-command/src/filters/mod.rs
Let me know if you have any thoughts!
=> Ported compact command to engine-q

Cargo.lock, crates/nu-command/Cargo.toml, crates/nu-command/src/core_commands/do_.rs, crates/nu-command/src/core_commands/for_.rs, crates/nu-command/src/filesystem/ls.rs, crates/nu-command/src/viewers/table.rs
Adds missing flags to:
* the -i part of do -i
* the -al part of ls -al (all but --du are now available)
* the -n part of table -n
* the -n part of for -n
=> Add missing flags to existing commands

crates/nu-cli/src/syntax_highlight.rs, crates/nu-color-config/src/shape_color.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/expression.rs, src/tests/test_strings.rs
fixes #574 
Also fixes string interpolation highlighting
=> Add single tick string interpolation

crates/nu-command/src/filesystem/ls.rs
=> Fix ls listing

crates/nu-engine/src/eval.rs
=> Handle external redirects better

Cargo.lock, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/syntax_shape.rs, crates/nu-protocol/src/ty.rs, src/tests/test_custom_commands.rs
Improved argument error for def function
closes #602
=> def argument check

crates/nu-parser/src/parser.rs, src/tests/test_parser.rs
=> Allow for and other commands missing positionals near keywords

crates/nu-command/src/filters/where_.rs, crates/nu-protocol/src/pipeline_data.rs
=> Preserve metatdata in where

crates/nu-command/src/filesystem/ls.rs, crates/nu-command/src/path/type.rs
changed `file_type`s to lowercase like `File` is now `file` and `Dir` is now `dir`.
=> revert file_types to lowercase

Cargo.lock, Cargo.toml, crates/nu-cli/Cargo.toml, crates/nu-cli/src/syntax_highlight.rs, crates/nu-parser/Cargo.toml, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/config.rs, src/logger.rs, src/main.rs
fix #629 
Adds parser tracing you can configure with the `log_level` config setting
=> Add parser tracing, fix 629

crates/nu-command/src/filters/get.rs, src/main.rs, src/tests/test_table_operations.rs
Make sure plugins are loaded and ready before parsing the config, so that the startup script can see them.
=> Plugin before config

crates/nu-engine/src/eval.rs
=> Fix perf regression with stmts

crates/nu-cli/src/syntax_highlight.rs, crates/nu-color-config/src/shape_color.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs
Do a similar highlight we just added for list/table to block/record
=> Highlight block and record

crates/nu-parser/src/lex.rs
=> Lex comment spans correctly

crates/nu-command/src/filesystem/cd.rs, crates/nu-command/src/filesystem/touch.rs, crates/nu-command/src/shells/enter.rs, crates/nu-protocol/src/value/mod.rs, src/main.rs
=> Fix directory change lag

crates/nu-command/src/filesystem/cd.rs, crates/nu-command/src/shells/enter.rs
This fixes a couple issues:
* `cd` now respects shells, so it will update the current shell with the directory being changed to
* `cd` and `enter` now use the canonical form, which makes paths a little nicer (no "foo/./src" types of paths)
=> More shell fixes

crates/nu-parser/src/type_check.rs, src/tests/test_type_check.rs
=> Allow int/float to coerce in type checker

Cargo.toml, crates/nu-command/Cargo.toml, crates/nu-command/src/default_context.rs, crates/nu-command/src/network/fetch.rs, crates/nu-command/src/network/mod.rs
Moves fetch to extra (see #661) and cleans up some code.
=> Move fetch to extra and clean up some code

crates/nu-parser/src/parser.rs
=> Expand external command names

crates/nu-parser/src/parser.rs
Fixes #683 
though we may also want to add the `which` support soon also
=> Fix path external

crates/nu-parser/src/parser.rs, src/tests/test_parser.rs
Fixes the case if a short flag has extra characters
=> Fix short flags with extra

src/main.rs
shift+tab should cycle you through the shells
=> silly keymap addition for quick shell changing

crates/nu-command/src/core_commands/hide.rs, crates/nu-command/src/core_commands/use_.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expression.rs, crates/nu-protocol/src/shell_error.rs
They now use more resilient internal command parsing and some early returns have been fixed. Also improved some errors on the engine side.
=> Cleanup of use and hide parsing

crates/nu-parser/src/parser.rs, src/tests/test_parser.rs
=> Don't panic on alias errors

crates/nu-command/src/system/run_external.rs, crates/nu-engine/src/eval.rs, crates/nu-parser/src/flatten.rs, crates/nu-parser/src/parser.rs, crates/nu-protocol/src/ast/expr.rs, crates/nu-protocol/src/ast/expression.rs
=> Add support for var/string interp for external names

crates/nu-command/src/system/run_external.rs, crates/nu-parser/src/parse_keywords.rs, crates/nu-protocol/src/engine/engine_state.rs, crates/nu-protocol/src/overlay.rs, src/main.rs
Also small refactors.
Fixes #726
=> Make env var eval order during "use" deterministic 

crates/nu-command/src/filesystem/ls.rs
=> Fix ls relative path and erroring on fake dir

crates/nu-command/src/filesystem/ls.rs
Takes the path diff only of the common prefix in the original pattern to avoid empty entries.
Fixes #758
=> Fix empty entry in ls

crates/nu-command/src/shells/enter.rs
=> Enter now requires a directory

crates/nu-command/src/filters/empty.rs
=> fix signature

crates/nu-parser/src/parser.rs, src/tests/test_parser.rs
fixes https://github.com/nushell/engine-q/issues/772
=> Improve env shorthand parse

crates/nu-command/src/default_context.rs, crates/nu-command/src/platform/mod.rs, crates/nu-command/src/platform/term_size.rs
=> add `term size` command

crates/nu-parser/src/parse_keywords.rs
=> allow `use` to parse quoted paths

crates/nu-command/src/system/run_external.rs, crates/nu-protocol/src/shell_error.rs, src/tests.rs
=> Make external app error uniform

crates/nu-cli/src/completions.rs
This lets you do flag completions for long flags, things like:
```
ls -<tab>
```
=> Add flag completions

crates/nu-command/src/system/run_external.rs
=> Only escape backslash on windows

crates/nu-command/src/filters/sort_by.rs
=> fix to retain ls_colors coloring from ls

crates/nu-command/src/filesystem/cd.rs, crates/nu-protocol/src/shell_error.rs
=> Fix cd-ing into a file

crates/nu-command/src/filters/find.rs, crates/nu-protocol/src/pipeline_data.rs
=> allow find to respect ls_colors

crates/nu-cli/src/lib.rs, crates/nu-cli/src/nu_highlight.rs, crates/nu-command/src/conversions/into/command.rs, crates/nu-command/src/core_commands/export.rs, crates/nu-command/src/core_commands/help.rs, crates/nu-command/src/core_commands/mod.rs, crates/nu-command/src/core_commands/tutor.rs, crates/nu-command/src/dataframe/eager/command.rs, crates/nu-command/src/date/command.rs, crates/nu-command/src/default_context.rs, crates/nu-command/src/hash/command.rs, crates/nu-command/src/math/command.rs, crates/nu-command/src/network/url/command.rs, crates/nu-command/src/path/command.rs, crates/nu-command/src/random/command.rs, crates/nu-command/src/strings/split/command.rs, crates/nu-command/src/strings/str_/case/command.rs, crates/nu-engine/src/documentation.rs, crates/nu-engine/src/eval.rs, src/main.rs
Adds syntax highlighting to `help`.
Adds `tutor`
=> Highlight help tutor

Cargo.lock, crates/nu-command/src/filesystem/ls.rs, crates/nu-command/src/system/run_external.rs, crates/nu-engine/Cargo.toml, crates/nu-engine/src/glob_from.rs, crates/nu-engine/src/lib.rs
```
> ^ls *.md
README.md  TODO.md
```
```
rg string *.md
TODO.md
68:        --flag: string(custom-completion),   ????
```
=> Allow external args to expand globs

crates/nu-command/src/network/fetch.rs
allow to add more extra headers with two format ：
1. ``` fetch -H [k1 val1 k2 val2] url.com```
2. ``` fetch -H [[[k1 k2]; [val1 val2]] url.com```
=> allow fetch command to add custom headers

crates/nu-command/src/filters/sort_by.rs
This adds support for Floats to sort-by...
=> add support for Floats for sort-by

Cargo.lock, src/reedline_config.rs, src/repl.rs
Rename `ContextMenu` to `CompletionMenu`
Supply the completer directly to the line editor
(description of your pull request here)
=> Accomodate reedline#270

crates/nu-engine/src/eval.rs, crates/nu-protocol/src/engine/stack.rs
Before:
```
Error: nu::shell::type_mismatch (link)
× Type mismatch during operation.
╭─[entry #1:1:1]
1 │ benchmark { echo a | each { $it + 10 } | length }
·                  ┬              ┬ ─┬
·                  │              │  ╰── int
·                  │              ╰── type mismatch for operator
·                  ╰── string
╰────
```
Now:
```
Error: nu::shell::type_mismatch (link)
× Type mismatch during operation.
╭─[entry #8:1:1]
1 │ benchmark { echo a | each { $it + 10 } | length }
·                             ─┬─ ┬ ─┬
·                              │  │  ╰── int
·                              │  ╰── type mismatch for operator
·                              ╰── string
╰────
```
Fwiw: if we can in the future, I'd like to have both, but for now the use site is closer to the …
=> Variables should error on use rather than value span

crates/nu-protocol/src/value/mod.rs, src/tests/test_table_operations.rs
Try to solve https://github.com/nushell/engine-q/issues/850
=> Maybe solve the none bug?

crates/nu-plugin/src/plugin/declaration.rs
Adds a wait on the child created for the plugin to prevent zombies.
=> Wait on the plugin child to prevent zombies

crates/nu-command/src/filesystem/ls.rs
port the `--du` parameter to the `ls` command
=> add `--du` to `ls` command

crates/nu-command/src/filters/sort_by.rs
allows you to sort case-insensitively
=> add case-insensitive sorting

crates/nu-command/tests/commands/cal.rs
=> fix cal tests

crates/nu-cli/src/completions.rs
This adds better subcommand completions. You'll now be able to do a command completion even when there are spaces, like here:
```
str |
```
Or 
```
str up|
```
=> Improve subcommand completions

crates/nu-command/tests/commands/find.rs
=> fix find tests

crates/nu-command/tests/commands/lines.rs
=> fix lines tests

crates/nu-command/tests/commands/mod.rs, crates/nu-command/tests/commands/nth.rs
this fixes and adds in the nth.rs tests by adding nth.rs to mod.rs
=> add nth tests to mod.rs

crates/nu-command/tests/commands/sort_by.rs
fixed 4 of the sort_by tests having to do with ls_sort_by
=> fix some of the sort_by tests several more left to do

Cargo.lock, crates/nu-command/src/default_context.rs, crates/nu-command/src/platform/mod.rs, crates/nu-command/src/platform/reedline_commands/default_keybindings.rs, crates/nu-command/src/platform/reedline_commands/mod.rs
(description of your pull request here)
=> default keybindings command

crates/nu-command/src/platform/reedline_commands/list_keybindings.rs
I just thought these should be sorted.
=> Sort keystuff

Cargo.lock
(description of your pull request here)
=> Reedline bump

crates/nu-cli/src/completions.rs
This moves around some of the completion logic and fixes a few places where we were accidentally doing completions for commands twice in some cases.
fixes https://github.com/nushell/reedline/issues/300
=> Fix completion duplicates
